-- DROP ALL TABLES IN REVERSE DEPENDENCY ORDER

DROP TABLE prescription       CASCADE CONSTRAINTS;
DROP TABLE patient_drugs      CASCADE CONSTRAINTS;
DROP TABLE sells              CASCADE CONSTRAINTS;
DROP TABLE contract           CASCADE CONSTRAINTS;
DROP TABLE patients           CASCADE CONSTRAINTS;
DROP TABLE doctors            CASCADE CONSTRAINTS;
DROP TABLE pharmacy           CASCADE CONSTRAINTS;
DROP TABLE drugs              CASCADE CONSTRAINTS;
DROP TABLE pharma_comp        CASCADE CONSTRAINTS;
